name: End to End

on:
  push:
    branches:
      - main
      - master
      - feature/admin-dashbord
  pull_request:
    branches:
      - main
      - master
      - feature/admin-dashbord

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - run: npm install
      - name: Install dfx
        uses: dfinity/setup-dfx@main
        
      - name: Confirm successful installation
        run: dfx --version
    
      - name: install mops packages
        run: mops install
        
      - run: npm run ci
        env:
          CI: true
          REPLICA_PORT: 8000