name: mops test

on:
  push:
    branches:
      - main
      - master
      - feature/admin-dashbord
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: install mops packages
        run: mops install
      
      - run: echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

      - name: run tests
        run: mops test