name: mops test

on:
  push:
    branches:
      - main
      - master
      - feature/admin-dashbord
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1
      
      - name: Install DFINITY SDK (dfx non-interactive)
        run: |
          export DFXVM_NO_INTERACTION=1
          curl -fsSL https://sdk.dfinity.org/install.sh | bash
          echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
          
      - name: install mops packages
        run: mops install

      - name: run tests
        run: mops test