name: mops test

on:
  push:
    branches:
      - main
      - master
      - feature/admin-dashbord
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - name: Confirm installations
        run: |
          node --version
          dfx --version
          mops --version

      - name: install mops packages
        run: |
          npm install -g ic-mops
          mops install

      - name: run tests
        run: mops test --verbose --debug
