name: mops test

on:
  push:
    branches:
      - main
      - master
      - feature/admin-dashbord
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - name: Confirm successful installation
        run: dfx --version

      - name: install mops packages
        run: mops install

      - name: Print DFX info
        run: |
          dfx --version
          mops --version
          node --version
          
      - name: run tests
        run: mops test --verbose