name: mops test

on:
  push:
    branches:
      - main
      - master
      - feature/admin-dashbord
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - name: Install mops
        uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: Confirm installations
        run: |
          node --version
          dfx --version
          mops --version
      
      - name: Install wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH
          
      - name: Install mops packages
        run: mops install

      - name: Run tests
        run: mops test --verbose --debug